version: '3'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
  elixir:
    build:
      context: .
      args:
        DATABASE_URL: "postgres://postgres:postgres@postgres:5432/dnd_tracker_dev"
        SECRET_KEY_BASE: "QSQz4IytCEZqnSZZjaQRNezNOWRsH5aQBSBz0jlsseTCatfC38ZuBS/IEuxFfBEq"
    volumes:
      - ".:/app"
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    command: ["mix", "phx.server"]
